server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: ids_alerts
    static_configs:
      - targets: [localhost]
        labels:
          job: ids_alerts
          __path__: /var/ids-logs/alerts.jsonl
    pipeline_stages:
      - json:                   # parse the JSON log line
          expressions:
            timestamp: timestamp
            src_ip: src_ip
            dst_ip: dst_ip
            src_port: src_port
            dst_port: dst_port
            protocol: protocol
            score: score
            level: level
      - labels:                 # promote useful fields to labels
          level:
          src_ip:
          dst_ip:
      - timestamp:             # use the correct timestamp field
          source: timestamp
          format: RFC3339Nano
