stages:
  - lint
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

lint:
  stage: lint
  image: python:3.11-slim
  script:
    - pip install flake8
    - flake8 ids_iforest_package/ids_iforest
  allow_failure: true

test:
  stage: test
  image: python:3.11-slim
  before_script:
    - pip install -e ids_iforest_package
    - pip install pytest
  script:
    - pytest -q
  artifacts:
    when: always
    paths:
      - .pytest_cache/

build:
  stage: build
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  script:
    - docker build -f ids/Dockerfile -t ids_iforest:ci .
    - docker build -f attacker/Dockerfile -t ids_attacker:ci attacker
    - docker build -f web/Dockerfile -t ids_web:ci web
  rules:
    - if: $CI_COMMIT_BRANCH == "main"