services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: victim_web
    ports:
      - "8080:80"      # victim web page only
    networks:
      - idsnet

  ids:
    build:
      context: .
      dockerfile: ids/Dockerfile
    container_name: ids_iforest
    # Share the network namespace with 'web' so tshark sees traffic hitting Nginx
    network_mode: "service:web"
    depends_on:
      - web
    environment:
      IDS_CONFIG: /app/config/config.yml
    volumes:
      - ./config:/app/config:ro
      - ./models:/app/models:ro         # pre-trained model
      - ids-logs:/app/logs              # write alerts.csv and alerts.jsonl here
    cap_add:
      - NET_ADMIN
      - NET_RAW

  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: attacker
    depends_on:
      - web
    environment:
      - TARGET_HOST=web
      - TARGET_PORT=80
    networks:
      - idsnet

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki
    networks:
      - idsnet

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    volumes:
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - ids-logs:/var/ids-logs:ro  # read alerts.csv / alerts.jsonl from the same volume
      - promtail-positions:/var/lib/promtail
    networks:
      - idsnet

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_INSTALL_PLUGINS: ""
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - idsnet

networks:
  idsnet:
    driver: bridge

volumes:
  ids-logs:
  promtail-positions:
  loki_data:
