services:

  ids_iforest:
    build:
      context: .
      dockerfile: ./services/ids/Dockerfile
    container_name: ids_iforest
    # Share the network namespace with 'web' so tshark sees traffic hitting Nginx
    network_mode: "service:web"   # <-- critical: see web's traffic
    depends_on:
      - web
      - loki
      - promtail
    environment:
      IDS_CONFIG: /app/config/config.yml
      IFACE: eth0
      IDS_YELLOW_THRESHOLD: "0.00"
    volumes:
      - ./config:/app/config
      - ./models:/app/models         # pre-trained model
      - ids-logs:/app/logs
    # allow packet capture
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # By default our Dockerfile CMD runs:
    # ids-iforest-detect --config /app/config/config.yml

  attacker:
    build:
      context: ./services/attacker
    container_name: attacker
    environment:
      - TARGET_HOST=web
      - TARGET_PORT=80
    networks:
      - idsnet
    depends_on:
      - web
      - ids_iforest
      - promtail
      - loki
      - grafana
    cap_add:
      - NET_RAW
      - NET_ADMIN
    restart: unless-stopped

  web:
    build:
      context: ./services/web
    container_name: victim_web
    ports:
      - "8080:80"      # victim web page only
    networks:
      - idsnet

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: ["-config.file=/etc/loki/loki-config.yml"]
    ports:
      - "3100:3100"
    volumes:
      - ./services/monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki
    networks:
      - idsnet

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: ["-config.file=/etc/promtail/promtail-config.yml"]
    depends_on:
      - loki
    volumes:
      - ./services/monitoring/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - ids-logs:/var/ids-logs
      - promtail-positions:/var/lib/promtail
    networks:
      - idsnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_INSTALL_PLUGINS: ""
    volumes:
      - ./services/monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./services/monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./services/monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - idsnet

networks:
  idsnet:
    driver: bridge

volumes:
  ids-logs:
  promtail-positions:
  loki_data:
