services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: victim_web
    ports:
      - "8080:80"      # victim web page
      - "5000:5000"    # publish IDS UI from the shared netns (see ids service)
    networks:
      - idsnet

  ids:
    build:
      context: .
      dockerfile: ids/Dockerfile
    container_name: ids_iforest
    # Share the network namespace with 'web' so tshark sees traffic hitting Nginx
    network_mode: "service:web"
    depends_on:
      - web
    environment:
      IDS_CONFIG: /app/config/config.yml
    volumes:
      - ./config:/app/config:ro
      - ./models:/app/models:ro     # your pre-trained model from CSE-CIC-IDS2018
      - ./logs:/app/logs
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # (Don't add 'ports:' here; it's not supported in container: mode per Docker docs)

  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: attacker
    depends_on:
      - web
    environment:
      - TARGET_HOST=web
      - TARGET_PORT=80
    networks:
      - idsnet

networks:
  idsnet:
    driver: bridge
