server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml   # mount this path as a volume

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: ids_alerts_csv
    static_configs:
      - targets: [localhost]
        labels:
          job: ids_alerts
          __path__: /var/ids-logs/alerts.jsonl
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            level: level
            protocol: protocol
            src_ip: src_ip
            dst_ip: dst_ip
            score: score
      - labels:
          level:
          protocol:
      - timestamp:
          source: ts
          format: RFC3339Nano
