server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /run/promtail/positions/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: ids_alerts
    static_configs:
      - targets: [localhost]
        labels:
          job: ids_alerts
          __path__: /var/ids-logs/alerts.csv
    pipeline_stages:
      - drop:
          expression: '^timestamp,src_ip,dst_ip,src_port,dst_port,protocol,score,level$'
      - regex:
          # capture all CSV fields by name
          expression: '^(?P<timestamp>[^,]+),(?P<src_ip>[^,]+),(?P<dst_ip>[^,]+),(?P<src_port>[^,]+),(?P<dst_port>[^,]+),(?P<protocol>[^,]+),(?P<score>-?[0-9.]+),(?P<level>[^,]+)$'
      - timestamp:
          source: timestamp
          format: '2006-01-02T15:04:05.999999'
      - labels:
          src_ip:
          dst_ip:
          protocol:
          level:
      # generate JSON log line so | json | unwrap score works in queries
      - template:
          source: message
          template: >
            {"timestamp":"{{ .timestamp }}",
             "src_ip":"{{ .src_ip }}",
             "dst_ip":"{{ .dst_ip }}",
             "src_port":{{ .src_port }},
             "dst_port":{{ .dst_port }},
             "protocol":"{{ .protocol }}",
             "score":{{ .score }},
             "level":"{{ .level }}"}
      - output:
          source: message

  # scrape the JSON file for completeness (optional)
  - job_name: ids_alerts_json
    static_configs:
      - targets: [localhost]
        labels:
          job: ids_alerts_json
          __path__: /var/ids-logs/alerts.jsonl
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            src_ip: src_ip
            dst_ip: dst_ip
            src_port: src_port
            dst_port: dst_port
            protocol: protocol
            score: score
            level: level
      - labels:
          src_ip:
          dst_ip:
          protocol:
          level:
      - timestamp:
          source: ts
          format: RFC3339Nano
