# Default configuration for the ids_iforest project.
window_seconds: 10
bpf_filter: "tcp or udp"
feature_set: "extended"
contamination: 0.02
model_dir: "/app/models"
logs_dir: "/app/logs"
iface: "any"